name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
  NEXT_PUBLIC_IMAGE_OPTIMIZER_URL: ${{ secrets.NEXT_PUBLIC_IMAGE_OPTIMIZER_URL }}
  NEXT_PUBLIC_PADDLE_CLIENT_TOKEN: ${{ secrets.NEXT_PUBLIC_PADDLE_CLIENT_TOKEN }}

jobs:
  build-amd64:
    runs-on: runs-on=${{ github.run_id }}/runner=8cpu-linux-x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (AMD64)
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest-amd
            ghcr.io/${{ github.repository }}:${{ github.sha }}-amd
          build-args: |
            NEXT_PUBLIC_BASE_URL: ${{ env.NEXT_PUBLIC_BASE_URL }}
            NEXT_PUBLIC_IMAGE_OPTIMIZER_URL: ${{ env.NEXT_PUBLIC_IMAGE_OPTIMIZER_URL }}
            NEXT_PUBLIC_PADDLE_CLIENT_TOKEN: ${{ env.NEXT_PUBLIC_PADDLE_CLIENT_TOKEN }}

  build-arm64:
    runs-on: runs-on=${{ github.run_id }}/runner=8cpu-linux-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (ARM64)
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest-arm
            ghcr.io/${{ github.repository }}:${{ github.sha }}-arm
          build-args: |
            NEXT_PUBLIC_BASE_URL: ${{ env.NEXT_PUBLIC_BASE_URL }}
            NEXT_PUBLIC_IMAGE_OPTIMIZER_URL: ${{ env.NEXT_PUBLIC_IMAGE_OPTIMIZER_URL }}
            NEXT_PUBLIC_PADDLE_CLIENT_TOKEN: ${{ env.NEXT_PUBLIC_PADDLE_CLIENT_TOKEN }}

  build-merge:
    runs-on: ubuntu-latest

    needs:
      - build-amd64
      - build-arm64

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge
        run: |
          docker buildx imagetools create -t ghcr.io/${{ github.repository }}:latest \
              ghcr.io/${{ github.repository }}:latest-amd \
              ghcr.io/${{ github.repository }}:latest-arm